dataset:
  name: llff
  root_path: ../data/fern
  format: JPG
  img_downscale_factor: 8
  pose_recenter: True


detector:
  name: SuperPointDetector
  descriptor_dim: 256
  nms_radius: 4
  keypoint_threshold: 0.005
  max_keypoints: -1
  remove_borders: 4
  cuda: 1

matcher:
  name: SuperGlueMatcher
  descriptor_dim: 256
  weights: "outdoor"
  sinkhorn_iterations: 100
  match_threshold: 0.2
  cuda: 1