dataset:
  name: templeRing
  root_path: ../data/templeRing
  format: png

detector:
  name: SuperPointDetector
  descriptor_dim: 256
  nms_radius: 4
  keypoint_threshold: 0.005
  max_keypoints: -1
  remove_borders: 4
  cuda: 1

matcher:
  name: SuperGlueMatcher
  descriptor_dim: 256
  weights: "indoor"
  sinkhorn_iterations: 100
  match_threshold: 0.2
  cuda: 1

sfm:
  pnp_reprojection_thresh: 4.0
  pnp_kfrm_num: 2   # how many previous keyframes to use for pnp
  recon_kfrm_num: 2 # how many previous keyframes to use for reconstruct on current frame
  kfrm_interval: 1  # how many frames to skip for keyframe